### ISSUE TITLE
Canada - Family Day Missing

### ISSUE THREAD

**Issue by dmike3** [dcmeglio/hubitat-holidayswitcher#1]
Canada - Family Day Missing

Can you have this added?

**Comment by dcmeglio** [comment]
I’m just pulling from the Calendarific api. Unfortunately that means I have no control over what holidays are listed. Sorry.

**Comment by dmike3** [comment]
> I’m just pulling from the Calendarific api. Unfortunately that means I have no control over what holidays are listed. Sorry.

Strange. Their site shows Family Day. 

Wonder why I don't see it?

**Comment by dmike3** [comment]
I just pulled it through the following URL below. I can see it in the output.

https://calendarific.com/api/v2/holidays?api_key=apikey&country=CA&year=2020

**Comment by dcmeglio** [comment]
Hmm. I’ll take a closer look. Your country is set to Canada and you’re looking in all of the drop downs, correct?

**Comment by dmike3** [comment]
> Hmm. I’ll take a closer look. Your country is set to Canada and you’re looking in all of the drop downs, correct?

Correct. I've looked a few times thinking maybe I missed it.

What I did notice is that it's under Public Holidays. It doesn't look like you have a group created for these.

**Comment by dcmeglio** [comment]
It's not actually a public holiday in the API, it's a local holiday. Currently I'm only pulling national holidays because there are a lot of local holidays. I'll take a look.

**Comment by dcmeglio** [comment]
I added support for pulling local holidays. You'll now seen an additional dropdown in the app that shows Family Day in Canada.

**Comment by dmike3** [comment]
Awesome! Thank you.
